### ISSUE TITLE
Can't connect to GitHub with Workflow Builder

### ISSUE THREAD

**Issue by iryan2** [OctopusSamples/content-team-apps#20]
When stepping through the Workflow Builder (at https://o9rot8lk3g.execute-api.us-west-1.amazonaws.com/), I receive the following response after clicking "Next" on step titled "Log into GitHub":

```
{"message": "Forbidden"}
```

See screen recording for example:

https://user-images.githubusercontent.com/5858312/182071974-3139153b-98a3-48f3-b402-89b95634c60c.mov

Then, when I navigate back via the browser's back button, the workflow builder informs me that the connection was successful: 

![image](https://user-images.githubusercontent.com/5858312/182072096-4afcf8cd-20a3-41f7-b0d1-dc5fe858d125.png)

I haven't verified that it wasn't successful, but I believe it failed, as at no time did I authorise the Workflow Builder GH app.

**Comment by mcasperson** [comment]
The issue with the forbidden error message would be because the URL for the production instance of the workflow builder changed to https://octopusworkflowbuilder.octopus.com. 

The hostname https://o9rot8lk3g.execute-api.us-west-1.amazonaws.com is the raw API Gateway hostname, which always needs the API Gateway stage appended to the end i.e. https://o9rot8lk3g.execute-api.us-west-1.amazonaws.com/Development/#/.

The issue with the app saying it had successfully logged in even though you hadn't is definitely a bug though.

**Comment by mcasperson** [comment]
The frontend app now checks for the presence of a GitHub token before moving to the "Logged into Github" state. If the token does not exist, the app will return to the page that redirects the user to log into github.
